-- Local-dev seed. Not run in production.
-- Two tenants (acme + globex), each with one organization, and two users with crossed memberships:
--   alice@humane.test  -> '*' (full admin) @ acme org, accountant-like grants @ globex org
--   bob@humane.test    -> employee-like grants @ acme org
-- Passwords: "password123" for both.

-- ------------------------------------------------------------
-- public.reserved_slugs — first-party route + locale collisions blocked from tenant slugs.
-- This MUST be seeded before any tenant insert (the CHECK in public.tenants.tenant_slug fires).
-- ------------------------------------------------------------

insert into public.reserved_slugs (reserved_slug) values
  ('a'),
  ('admin'),
  ('affiliate'),
  ('agencies'),
  ('api'),
  ('app'),
  ('assets'),
  ('auth'),
  ('cdn'),
  ('en'),
  ('es'),
  ('pt'),
  ('health'),
  ('home'),
  ('legal'),
  ('maintenance'),
  ('me'),
  ('notifications'),
  ('public'),
  ('static'),
  ('support'),
  ('tenants'),
  ('www'),
  ('_next')
on conflict (reserved_slug) do nothing;

-- ------------------------------------------------------------
-- auth.users (profiles are created by the users_handle_created trigger)
-- ------------------------------------------------------------

insert into auth.users (
  instance_id, id, aud, role, email, encrypted_password,
  email_confirmed_at, raw_app_meta_data, raw_user_meta_data,
  created_at, updated_at,
  confirmation_token, email_change, email_change_token_new, recovery_token
)
values
  (
    '00000000-0000-0000-0000-000000000000',
    '00000000-0000-0000-0000-00000000a11c',
    'authenticated', 'authenticated',
    'alice@humane.test',
    crypt('password123', gen_salt('bf')),
    current_timestamp,
    '{"provider":"email","providers":["email"]}'::jsonb,
    '{"full_name":"Alice Owner"}'::jsonb,
    current_timestamp, current_timestamp,
    '', '', '', ''
  ),
  (
    '00000000-0000-0000-0000-000000000000',
    '00000000-0000-0000-0000-00000000b00b',
    'authenticated', 'authenticated',
    'bob@humane.test',
    crypt('password123', gen_salt('bf')),
    current_timestamp,
    '{"provider":"email","providers":["email"]}'::jsonb,
    '{"full_name":"Bob Employee"}'::jsonb,
    current_timestamp, current_timestamp,
    '', '', '', ''
  )
on conflict (id) do nothing;

insert into auth.identities (
  provider_id, user_id, identity_data, provider,
  last_sign_in_at, created_at, updated_at
)
values
  (
    '00000000-0000-0000-0000-00000000a11c',
    '00000000-0000-0000-0000-00000000a11c',
    '{"sub":"00000000-0000-0000-0000-00000000a11c","email":"alice@humane.test"}'::jsonb,
    'email',
    current_timestamp, current_timestamp, current_timestamp
  ),
  (
    '00000000-0000-0000-0000-00000000b00b',
    '00000000-0000-0000-0000-00000000b00b',
    '{"sub":"00000000-0000-0000-0000-00000000b00b","email":"bob@humane.test"}'::jsonb,
    'email',
    current_timestamp, current_timestamp, current_timestamp
  )
on conflict (provider_id, provider) do nothing;

-- ------------------------------------------------------------
-- tenants (serial PKs — fixed for seed predictability)
-- ------------------------------------------------------------

insert into public.tenants (tenant_id, tenant_slug, tenant_name)
values
  (1, 'acme', 'Acme SpA'),
  (2, 'globex', 'Globex SA')
on conflict (tenant_id) do nothing;

select setval(pg_get_serial_sequence('public.tenants', 'tenant_id'), (select max(tenant_id) from public.tenants));

-- ------------------------------------------------------------
-- organizations — one default org per tenant, slug + name mirror the tenant
-- ------------------------------------------------------------

insert into public.organizations (organization_id, tenant_id, organization_slug, organization_name)
values
  (1, 1, 'acme', 'Acme SpA'),
  (2, 2, 'globex', 'Globex SA')
on conflict (organization_id) do nothing;

select setval(pg_get_serial_sequence('public.organizations', 'organization_id'), (select max(organization_id) from public.organizations));

-- ------------------------------------------------------------
-- memberships + membership_permissions
-- ------------------------------------------------------------
-- Memberships now carry their own serial PK. Seed inserts are accepted out of the
-- gate (profile_id set + membership_accepted_at = now) so the seeded users skip the
-- pending-invite flow. Permission rows reference membership_id, so we use CTEs to
-- thread the freshly-inserted ids into the grants below.

with seeded_memberships as (
  insert into public.memberships (organization_id, profile_id, membership_accepted_at)
  values
    (1, '00000000-0000-0000-0000-00000000a11c', current_timestamp),
    (2, '00000000-0000-0000-0000-00000000a11c', current_timestamp),
    (1, '00000000-0000-0000-0000-00000000b00b', current_timestamp)
  returning membership_id, organization_id, profile_id
)
-- Alice: '*' (full admin) on acme org; "accountant"-like grants on globex org.
-- Bob: "employee"-like grants on acme org.
insert into public.membership_permissions (membership_id, permission_id)
select sm.membership_id, perm.permission_id
from seeded_memberships sm
join (values
  (1, '00000000-0000-0000-0000-00000000a11c'::uuid, '*'::extensions.citext),
  (2, '00000000-0000-0000-0000-00000000a11c'::uuid, 'payroll_run'::extensions.citext),
  (2, '00000000-0000-0000-0000-00000000a11c'::uuid, 'payroll_view'::extensions.citext),
  (2, '00000000-0000-0000-0000-00000000a11c'::uuid, 'previred_export'::extensions.citext),
  (2, '00000000-0000-0000-0000-00000000a11c'::uuid, 'lre_export'::extensions.citext),
  (2, '00000000-0000-0000-0000-00000000a11c'::uuid, 'banco_export'::extensions.citext),
  (2, '00000000-0000-0000-0000-00000000a11c'::uuid, 'terminations_create'::extensions.citext),
  (1, '00000000-0000-0000-0000-00000000b00b'::uuid, 'vacations_request'::extensions.citext)
) as perm (organization_id, profile_id, permission_id)
  on perm.organization_id = sm.organization_id and perm.profile_id = sm.profile_id;

-- Mark seed users as onboarded so manual end-to-end testing skips the /auth/onboarding nudge.
update public.profiles
  set profile_onboarded_at = current_timestamp
  where profile_id in (
    '00000000-0000-0000-0000-00000000a11c',
    '00000000-0000-0000-0000-00000000b00b'
  );

-- ------------------------------------------------------------
-- addresses — Chile administrative hierarchy (CL)
-- level0 = country, level1 = region (ISO 3166-2), level2 = province, level3 = commune
-- 1 country · 16 regions · 56 provinces · 345 communes
-- ------------------------------------------------------------

-- Level 0: Country
insert into public.addresses_level0 (address_level0_id, address_level0_name, address_level0_emoji) values
  ('AF', 'Afghanistan', '🇦🇫'),
  ('AX', 'Åland Islands', '🇦🇽'),
  ('AL', 'Albania', '🇦🇱'),
  ('DZ', 'Algeria', '🇩🇿'),
  ('AS', 'American Samoa', '🇦🇸'),
  ('AD', 'Andorra', '🇦🇩'),
  ('AO', 'Angola', '🇦🇴'),
  ('AI', 'Anguilla', '🇦🇮'),
  ('AQ', 'Antarctica', '🇦🇶'),
  ('AG', 'Antigua and Barbuda', '🇦🇬'),
  ('AR', 'Argentina', '🇦🇷'),
  ('AM', 'Armenia', '🇦🇲'),
  ('AW', 'Aruba', '🇦🇼'),
  ('AU', 'Australia', '🇦🇺'),
  ('AT', 'Austria', '🇦🇹'),
  ('AZ', 'Azerbaijan', '🇦🇿'),
  ('BS', 'Bahamas', '🇧🇸'),
  ('BH', 'Bahrain', '🇧🇭'),
  ('BD', 'Bangladesh', '🇧🇩'),
  ('BB', 'Barbados', '🇧🇧'),
  ('BY', 'Belarus', '🇧🇾'),
  ('BE', 'Belgium', '🇧🇪'),
  ('BZ', 'Belize', '🇧🇿'),
  ('BJ', 'Benin', '🇧🇯'),
  ('BM', 'Bermuda', '🇧🇲'),
  ('BT', 'Bhutan', '🇧🇹'),
  ('BO', 'Bolivia', '🇧🇴'),
  ('BQ', 'Bonaire, Sint Eustatius and Saba', '🇧🇶'),
  ('BA', 'Bosnia and Herzegovina', '🇧🇦'),
  ('BW', 'Botswana', '🇧🇼'),
  ('BV', 'Bouvet Island', '🇧🇻'),
  ('BR', 'Brazil', '🇧🇷'),
  ('IO', 'British Indian Ocean Territory', '🇮🇴'),
  ('BN', 'Brunei Darussalam', '🇧🇳'),
  ('BG', 'Bulgaria', '🇧🇬'),
  ('BF', 'Burkina Faso', '🇧🇫'),
  ('BI', 'Burundi', '🇧🇮'),
  ('CV', 'Cabo Verde', '🇨🇻'),
  ('KH', 'Cambodia', '🇰🇭'),
  ('CM', 'Cameroon', '🇨🇲'),
  ('CA', 'Canada', '🇨🇦'),
  ('KY', 'Cayman Islands', '🇰🇾'),
  ('CF', 'Central African Republic', '🇨🇫'),
  ('TD', 'Chad', '🇹🇩'),
  ('CL', 'Chile', '🇨🇱'),
  ('CN', 'China', '🇨🇳'),
  ('CX', 'Christmas Island', '🇨🇽'),
  ('CC', 'Cocos (Keeling) Islands', '🇨🇨'),
  ('CO', 'Colombia', '🇨🇴'),
  ('KM', 'Comoros', '🇰🇲'),
  ('CG', 'Congo', '🇨🇬'),
  ('CD', 'Congo, Democratic Republic of the', '🇨🇩'),
  ('CK', 'Cook Islands', '🇨🇰'),
  ('CR', 'Costa Rica', '🇨🇷'),
  ('CI', 'Côte d''Ivoire', '🇨🇮'),
  ('HR', 'Croatia', '🇭🇷'),
  ('CU', 'Cuba', '🇨🇺'),
  ('CW', 'Curaçao', '🇨🇼'),
  ('CY', 'Cyprus', '🇨🇾'),
  ('CZ', 'Czechia', '🇨🇿'),
  ('DK', 'Denmark', '🇩🇰'),
  ('DJ', 'Djibouti', '🇩🇯'),
  ('DM', 'Dominica', '🇩🇲'),
  ('DO', 'Dominican Republic', '🇩🇴'),
  ('EC', 'Ecuador', '🇪🇨'),
  ('EG', 'Egypt', '🇪🇬'),
  ('SV', 'El Salvador', '🇸🇻'),
  ('GQ', 'Equatorial Guinea', '🇬🇶'),
  ('ER', 'Eritrea', '🇪🇷'),
  ('EE', 'Estonia', '🇪🇪'),
  ('SZ', 'Eswatini', '🇸🇿'),
  ('ET', 'Ethiopia', '🇪🇹'),
  ('FK', 'Falkland Islands (Malvinas)', '🇫🇰'),
  ('FO', 'Faroe Islands', '🇫🇴'),
  ('FJ', 'Fiji', '🇫🇯'),
  ('FI', 'Finland', '🇫🇮'),
  ('FR', 'France', '🇫🇷'),
  ('GF', 'French Guiana', '🇬🇫'),
  ('PF', 'French Polynesia', '🇵🇫'),
  ('TF', 'French Southern Territories', '🇹🇫'),
  ('GA', 'Gabon', '🇬🇦'),
  ('GM', 'Gambia', '🇬🇲'),
  ('GE', 'Georgia', '🇬🇪'),
  ('DE', 'Germany', '🇩🇪'),
  ('GH', 'Ghana', '🇬🇭'),
  ('GI', 'Gibraltar', '🇬🇮'),
  ('GR', 'Greece', '🇬🇷'),
  ('GL', 'Greenland', '🇬🇱'),
  ('GD', 'Grenada', '🇬🇩'),
  ('GP', 'Guadeloupe', '🇬🇵'),
  ('GU', 'Guam', '🇬🇺'),
  ('GT', 'Guatemala', '🇬🇹'),
  ('GG', 'Guernsey', '🇬🇬'),
  ('GN', 'Guinea', '🇬🇳'),
  ('GW', 'Guinea-Bissau', '🇬🇼'),
  ('GY', 'Guyana', '🇬🇾'),
  ('HT', 'Haiti', '🇭🇹'),
  ('HM', 'Heard Island and McDonald Islands', '🇭🇲'),
  ('VA', 'Holy See', '🇻🇦'),
  ('HN', 'Honduras', '🇭🇳'),
  ('HK', 'Hong Kong', '🇭🇰'),
  ('HU', 'Hungary', '🇭🇺'),
  ('IS', 'Iceland', '🇮🇸'),
  ('IN', 'India', '🇮🇳'),
  ('ID', 'Indonesia', '🇮🇩'),
  ('IR', 'Iran (Islamic Republic of)', '🇮🇷'),
  ('IQ', 'Iraq', '🇮🇶'),
  ('IE', 'Ireland', '🇮🇪'),
  ('IM', 'Isle of Man', '🇮🇲'),
  ('IL', 'Israel', '🇮🇱'),
  ('IT', 'Italy', '🇮🇹'),
  ('JM', 'Jamaica', '🇯🇲'),
  ('JP', 'Japan', '🇯🇵'),
  ('JE', 'Jersey', '🇯🇪'),
  ('JO', 'Jordan', '🇯🇴'),
  ('KZ', 'Kazakhstan', '🇰🇿'),
  ('KE', 'Kenya', '🇰🇪'),
  ('KI', 'Kiribati', '🇰🇮'),
  ('KP', 'Korea (Democratic People''s Republic of)', '🇰🇵'),
  ('KR', 'Korea, Republic of', '🇰🇷'),
  ('KW', 'Kuwait', '🇰🇼'),
  ('KG', 'Kyrgyzstan', '🇰🇬'),
  ('LA', 'Lao', '🇱🇦'),
  ('LV', 'Latvia', '🇱🇻'),
  ('LB', 'Lebanon', '🇱🇧'),
  ('LS', 'Lesotho', '🇱🇸'),
  ('LR', 'Liberia', '🇱🇷'),
  ('LY', 'Libya', '🇱🇾'),
  ('LI', 'Liechtenstein', '🇱🇮'),
  ('LT', 'Lithuania', '🇱🇹'),
  ('LU', 'Luxembourg', '🇱🇺'),
  ('MO', 'Macao', '🇲🇴'),
  ('MG', 'Madagascar', '🇲🇬'),
  ('MW', 'Malawi', '🇲🇼'),
  ('MY', 'Malaysia', '🇲🇾'),
  ('MV', 'Maldives', '🇲🇻'),
  ('ML', 'Mali', '🇲🇱'),
  ('MT', 'Malta', '🇲🇹'),
  ('MH', 'Marshall Islands', '🇲🇭'),
  ('MQ', 'Martinique', '🇲🇶'),
  ('MR', 'Mauritania', '🇲🇷'),
  ('MU', 'Mauritius', '🇲🇺'),
  ('YT', 'Mayotte', '🇾🇹'),
  ('MX', 'Mexico', '🇲🇽'),
  ('FM', 'Micronesia (Federated States of)', '🇫🇲'),
  ('MD', 'Moldova, Republic of', '🇲🇩'),
  ('MC', 'Monaco', '🇲🇨'),
  ('MN', 'Mongolia', '🇲🇳'),
  ('ME', 'Montenegro', '🇲🇪'),
  ('MS', 'Montserrat', '🇲🇸'),
  ('MA', 'Morocco', '🇲🇦'),
  ('MZ', 'Mozambique', '🇲🇿'),
  ('MM', 'Myanmar', '🇲🇲'),
  ('NA', 'Namibia', '🇳🇦'),
  ('NR', 'Nauru', '🇳🇷'),
  ('NP', 'Nepal', '🇳🇵'),
  ('NL', 'Netherlands', '🇳🇱'),
  ('NC', 'New Caledonia', '🇳🇨'),
  ('NZ', 'New Zealand', '🇳🇿'),
  ('NI', 'Nicaragua', '🇳🇮'),
  ('NE', 'Niger', '🇳🇪'),
  ('NG', 'Nigeria', '🇳🇬'),
  ('NU', 'Niue', '🇳🇺'),
  ('NF', 'Norfolk Island', '🇳🇫'),
  ('MK', 'North Macedonia', '🇲🇰'),
  ('MP', 'Northern Mariana Islands', '🇲🇵'),
  ('NO', 'Norway', '🇳🇴'),
  ('OM', 'Oman', '🇴🇲'),
  ('PK', 'Pakistan', '🇵🇰'),
  ('PW', 'Palau', '🇵🇼'),
  ('PS', 'Palestine, State of', '🇵🇸'),
  ('PA', 'Panama', '🇵🇦'),
  ('PG', 'Papua New Guinea', '🇵🇬'),
  ('PY', 'Paraguay', '🇵🇾'),
  ('PE', 'Peru', '🇵🇪'),
  ('PH', 'Philippines', '🇵🇭'),
  ('PN', 'Pitcairn', '🇵🇳'),
  ('PL', 'Poland', '🇵🇱'),
  ('PT', 'Portugal', '🇵🇹'),
  ('PR', 'Puerto Rico', '🇵🇷'),
  ('QA', 'Qatar', '🇶🇦'),
  ('RE', 'Réunion', '🇷🇪'),
  ('RO', 'Romania', '🇷🇴'),
  ('RU', 'Russian Federation', '🇷🇺'),
  ('RW', 'Rwanda', '🇷🇼'),
  ('BL', 'Saint Barthélemy', '🇧🇱'),
  ('SH', 'Saint Helena, Ascension and Tristan da Cunha', '🇸🇭'),
  ('KN', 'Saint Kitts and Nevis', '🇰🇳'),
  ('LC', 'Saint Lucia', '🇱🇨'),
  ('MF', 'Saint Martin (French part)', '🇲🇫'),
  ('PM', 'Saint Pierre and Miquelon', '🇵🇲'),
  ('VC', 'Saint Vincent and the Grenadines', '🇻🇨'),
  ('WS', 'Samoa', '🇼🇸'),
  ('SM', 'San Marino', '🇸🇲'),
  ('ST', 'Sao Tome and Principe', '🇸🇹'),
  ('SA', 'Saudi Arabia', '🇸🇦'),
  ('SN', 'Senegal', '🇸🇳'),
  ('RS', 'Serbia', '🇷🇸'),
  ('SC', 'Seychelles', '🇸🇨'),
  ('SL', 'Sierra Leone', '🇸🇱'),
  ('SG', 'Singapore', '🇸🇬'),
  ('SX', 'Sint Maarten (Dutch part)', '🇸🇽'),
  ('SK', 'Slovakia', '🇸🇰'),
  ('SI', 'Slovenia', '🇸🇮'),
  ('SB', 'Solomon Islands', '🇸🇧'),
  ('SO', 'Somalia', '🇸🇴'),
  ('ZA', 'South Africa', '🇿🇦'),
  ('GS', 'South Georgia and the South Sandwich Islands', '🇬🇸'),
  ('SS', 'South Sudan', '🇸🇸'),
  ('ES', 'Spain', '🇪🇸'),
  ('LK', 'Sri Lanka', '🇱🇰'),
  ('SD', 'Sudan', '🇸🇩'),
  ('SR', 'Suriname', '🇸🇷'),
  ('SJ', 'Svalbard and Jan Mayen', '🇸🇯'),
  ('SE', 'Sweden', '🇸🇪'),
  ('CH', 'Switzerland', '🇨🇭'),
  ('SY', 'Syrian Arab Republic', '🇸🇾'),
  ('TW', 'Taiwan, Province of China', '🇹🇼'),
  ('TJ', 'Tajikistan', '🇹🇯'),
  ('TZ', 'Tanzania, United Republic of', '🇹🇿'),
  ('TH', 'Thailand', '🇹🇭'),
  ('TL', 'Timor-Leste', '🇹🇱'),
  ('TG', 'Togo', '🇹🇬'),
  ('TK', 'Tokelau', '🇹🇰'),
  ('TO', 'Tonga', '🇹🇴'),
  ('TT', 'Trinidad and Tobago', '🇹🇹'),
  ('TN', 'Tunisia', '🇹🇳'),
  ('TR', 'Turkey', '🇹🇷'),
  ('TM', 'Turkmenistan', '🇹🇲'),
  ('TC', 'Turks and Caicos Islands', '🇹🇨'),
  ('TV', 'Tuvalu', '🇹🇻'),
  ('UG', 'Uganda', '🇺🇬'),
  ('UA', 'Ukraine', '🇺🇦'),
  ('AE', 'United Arab Emirates', '🇦🇪'),
  ('GB', 'United Kingdom of Great Britain and Northern Ireland', '🇬🇧'),
  ('US', 'United States of America', '🇺🇸'),
  ('UM', 'United States Minor Outlying Islands', '🇺🇲'),
  ('UY', 'Uruguay', '🇺🇾'),
  ('UZ', 'Uzbekistan', '🇺🇿'),
  ('VU', 'Vanuatu', '🇻🇺'),
  ('VE', 'Venezuela', '🇻🇪'),
  ('VN', 'Viet Nam', '🇻🇳'),
  ('VG', 'Virgin Islands (British)', '🇻🇬'),
  ('VI', 'Virgin Islands (U.S.)', '🇻🇮'),
  ('WF', 'Wallis and Futuna', '🇼🇫'),
  ('EH', 'Western Sahara', '🇪🇭'),
  ('YE', 'Yemen', '🇾🇪'),
  ('ZM', 'Zambia', '🇿🇲'),
  ('ZW', 'Zimbabwe', '🇿🇼')
on conflict (address_level0_id) do nothing;

-- Level 1: Regions (ISO 3166-2:CL)
insert into public.addresses_level1 (address_level0_id, address_level1_id, address_level1_name) values
  ('CL', 'CL-AI', 'Aysén del General Carlos Ibañez del Campo'),
  ('CL', 'CL-AN', 'Antofagasta'),
  ('CL', 'CL-AP', 'Arica y Parinacota'),
  ('CL', 'CL-AR', 'La Araucanía'),
  ('CL', 'CL-AT', 'Atacama'),
  ('CL', 'CL-BI', 'Biobío'),
  ('CL', 'CL-CO', 'Coquimbo'),
  ('CL', 'CL-LI', 'Libertador General Bernardo O''Higgins'),
  ('CL', 'CL-LL', 'Los Lagos'),
  ('CL', 'CL-LR', 'Los Ríos'),
  ('CL', 'CL-MA', 'Magallanes'),
  ('CL', 'CL-ML', 'Maule'),
  ('CL', 'CL-NB', 'Ñuble'),
  ('CL', 'CL-RM', 'Región Metropolitana de Santiago'),
  ('CL', 'CL-TA', 'Tarapacá'),
  ('CL', 'CL-VS', 'Valparaíso')
on conflict (address_level0_id, address_level1_id) do nothing;

-- Level 2: Provinces
insert into public.addresses_level2 (address_level0_id, address_level1_id, address_level2_id, address_level2_name) values
  ('CL', 'CL-AP', 'arica', 'Arica'),
  ('CL', 'CL-AP', 'parinacota', 'Parinacota'),
  ('CL', 'CL-TA', 'el-tamarugal', 'El Tamarugal'),
  ('CL', 'CL-TA', 'iquique', 'Iquique'),
  ('CL', 'CL-AN', 'tocopilla', 'Tocopilla'),
  ('CL', 'CL-AN', 'el-loa', 'El Loa'),
  ('CL', 'CL-AN', 'antofagasta', 'Antofagasta'),
  ('CL', 'CL-AT', 'chanaral', 'Chañaral'),
  ('CL', 'CL-AT', 'copiapo', 'Copiapó'),
  ('CL', 'CL-AT', 'huasco', 'Huasco'),
  ('CL', 'CL-CO', 'elqui', 'Elqui'),
  ('CL', 'CL-CO', 'limari', 'Limarí'),
  ('CL', 'CL-CO', 'choapa', 'Choapa'),
  ('CL', 'CL-VS', 'petorca', 'Petorca'),
  ('CL', 'CL-VS', 'los-andes', 'Los Andes'),
  ('CL', 'CL-VS', 'san-felipe', 'San Felipe de Aconcagua'),
  ('CL', 'CL-VS', 'quillota', 'Quillota'),
  ('CL', 'CL-VS', 'valparaiso', 'Valparaíso'),
  ('CL', 'CL-VS', 'marga-marga', 'Marga Marga'),
  ('CL', 'CL-VS', 'san-antonio', 'San Antonio'),
  ('CL', 'CL-VS', 'isla-de-pascua', 'Isla de Pascua'),
  ('CL', 'CL-LI', 'cachapoal', 'Cachapoal'),
  ('CL', 'CL-LI', 'colchagua', 'Colchagua'),
  ('CL', 'CL-LI', 'cardenal-caro', 'Cardenal Caro'),
  ('CL', 'CL-ML', 'curico', 'Curicó'),
  ('CL', 'CL-ML', 'talca', 'Talca'),
  ('CL', 'CL-ML', 'linares', 'Linares'),
  ('CL', 'CL-ML', 'cauquenes', 'Cauquenes'),
  ('CL', 'CL-NB', 'itata', 'Itata'),
  ('CL', 'CL-NB', 'diguillin', 'Diguillín'),
  ('CL', 'CL-NB', 'punilla', 'Punilla'),
  ('CL', 'CL-BI', 'biobio', 'Biobío'),
  ('CL', 'CL-BI', 'concepcion', 'Concepción'),
  ('CL', 'CL-BI', 'arauco', 'Arauco'),
  ('CL', 'CL-AR', 'malleco', 'Malleco'),
  ('CL', 'CL-AR', 'cautin', 'Cautín'),
  ('CL', 'CL-LR', 'valdivia', 'Valdivia'),
  ('CL', 'CL-LR', 'ranco', 'Ranco'),
  ('CL', 'CL-LL', 'osorno', 'Osorno'),
  ('CL', 'CL-LL', 'llanquihue', 'Llanquihue'),
  ('CL', 'CL-LL', 'chiloe', 'Chiloé'),
  ('CL', 'CL-LL', 'palena', 'Palena'),
  ('CL', 'CL-AI', 'coihaique', 'Coihaique'),
  ('CL', 'CL-AI', 'aysen', 'Aysén'),
  ('CL', 'CL-AI', 'general-carrera', 'General Carrera'),
  ('CL', 'CL-AI', 'capitan-prat', 'Capitán Prat'),
  ('CL', 'CL-MA', 'ultima-esperanza', 'Última Esperanza'),
  ('CL', 'CL-MA', 'magallanes', 'Magallanes'),
  ('CL', 'CL-MA', 'tierra-del-fuego', 'Tierra del Fuego'),
  ('CL', 'CL-MA', 'antartica-chilena', 'Antártica Chilena'),
  ('CL', 'CL-RM', 'chacabuco', 'Chacabuco'),
  ('CL', 'CL-RM', 'cordillera', 'Cordillera'),
  ('CL', 'CL-RM', 'maipo', 'Maipo'),
  ('CL', 'CL-RM', 'talagante', 'Talagante'),
  ('CL', 'CL-RM', 'melipilla', 'Melipilla'),
  ('CL', 'CL-RM', 'santiago', 'Santiago')
on conflict (address_level0_id, address_level1_id, address_level2_id) do nothing;

-- Level 3: Communes — CL-AP
insert into public.addresses_level3 (address_level0_id, address_level1_id, address_level2_id, address_level3_id, address_level3_name) values
  ('CL', 'CL-AP', 'arica', 'arica', 'Arica'),
  ('CL', 'CL-AP', 'arica', 'camarones', 'Camarones'),
  ('CL', 'CL-AP', 'parinacota', 'general-lagos', 'General Lagos'),
  ('CL', 'CL-AP', 'parinacota', 'putre', 'Putre'),
  ('CL', 'CL-TA', 'el-tamarugal', 'camina', 'Camiña'),
  ('CL', 'CL-TA', 'el-tamarugal', 'colchane', 'Colchane'),
  ('CL', 'CL-TA', 'el-tamarugal', 'huara', 'Huara'),
  ('CL', 'CL-TA', 'el-tamarugal', 'pica', 'Pica'),
  ('CL', 'CL-TA', 'el-tamarugal', 'pozo-almonte', 'Pozo Almonte'),
  ('CL', 'CL-TA', 'iquique', 'iquique', 'Iquique'),
  ('CL', 'CL-TA', 'iquique', 'alto-hospicio', 'Alto Hospicio'),
  ('CL', 'CL-AN', 'tocopilla', 'maria-elena', 'María Elena'),
  ('CL', 'CL-AN', 'tocopilla', 'tocopilla', 'Tocopilla'),
  ('CL', 'CL-AN', 'el-loa', 'calama', 'Calama'),
  ('CL', 'CL-AN', 'el-loa', 'ollague', 'Ollagüe'),
  ('CL', 'CL-AN', 'el-loa', 'san-pedro-de-atacama', 'San Pedro de Atacama'),
  ('CL', 'CL-AN', 'antofagasta', 'antofagasta', 'Antofagasta'),
  ('CL', 'CL-AN', 'antofagasta', 'mejillones', 'Mejillones'),
  ('CL', 'CL-AN', 'antofagasta', 'sierra-gorda', 'Sierra Gorda'),
  ('CL', 'CL-AN', 'antofagasta', 'taltal', 'Taltal'),
  ('CL', 'CL-AT', 'chanaral', 'chanaral', 'Chañaral'),
  ('CL', 'CL-AT', 'chanaral', 'diego-de-almagro', 'Diego de Almagro'),
  ('CL', 'CL-AT', 'copiapo', 'copiapo', 'Copiapó'),
  ('CL', 'CL-AT', 'copiapo', 'caldera', 'Caldera'),
  ('CL', 'CL-AT', 'copiapo', 'tierra-amarilla', 'Tierra Amarilla'),
  ('CL', 'CL-AT', 'huasco', 'vallenar', 'Vallenar'),
  ('CL', 'CL-AT', 'huasco', 'freirina', 'Freirina'),
  ('CL', 'CL-AT', 'huasco', 'huasco', 'Huasco'),
  ('CL', 'CL-AT', 'huasco', 'alto-del-carmen', 'Alto del Carmen'),
  ('CL', 'CL-CO', 'elqui', 'andacollo', 'Andacollo'),
  ('CL', 'CL-CO', 'elqui', 'coquimbo', 'Coquimbo'),
  ('CL', 'CL-CO', 'elqui', 'la-higuera', 'La Higuera'),
  ('CL', 'CL-CO', 'elqui', 'la-serena', 'La Serena'),
  ('CL', 'CL-CO', 'elqui', 'paiguano', 'Paiguano'),
  ('CL', 'CL-CO', 'elqui', 'vicuna', 'Vicuña'),
  ('CL', 'CL-CO', 'limari', 'ovalle', 'Ovalle'),
  ('CL', 'CL-CO', 'limari', 'rio-hurtado', 'Río Hurtado'),
  ('CL', 'CL-CO', 'limari', 'monte-patria', 'Monte Patria'),
  ('CL', 'CL-CO', 'limari', 'combarbala', 'Combarbalá'),
  ('CL', 'CL-CO', 'limari', 'punitaqui', 'Punitaqui'),
  ('CL', 'CL-CO', 'choapa', 'illapel', 'Illapel'),
  ('CL', 'CL-CO', 'choapa', 'salamanca', 'Salamanca'),
  ('CL', 'CL-CO', 'choapa', 'los-vilos', 'Los Vilos'),
  ('CL', 'CL-CO', 'choapa', 'canela', 'Canela'),
  ('CL', 'CL-VS', 'petorca', 'la-ligua', 'La Ligua'),
  ('CL', 'CL-VS', 'petorca', 'cabildo', 'Cabildo'),
  ('CL', 'CL-VS', 'petorca', 'zapallar', 'Zapallar'),
  ('CL', 'CL-VS', 'petorca', 'papudo', 'Papudo'),
  ('CL', 'CL-VS', 'petorca', 'petorca', 'Petorca'),
  ('CL', 'CL-VS', 'los-andes', 'los-andes', 'Los Andes'),
  ('CL', 'CL-VS', 'los-andes', 'san-esteban', 'San Esteban'),
  ('CL', 'CL-VS', 'los-andes', 'calle-larga', 'Calle Larga'),
  ('CL', 'CL-VS', 'los-andes', 'rinconada', 'Rinconada'),
  ('CL', 'CL-VS', 'san-felipe', 'san-felipe', 'San Felipe'),
  ('CL', 'CL-VS', 'san-felipe', 'llaillay', 'Llaillay'),
  ('CL', 'CL-VS', 'san-felipe', 'putaendo', 'Putaendo'),
  ('CL', 'CL-VS', 'san-felipe', 'santa-maria', 'Santa María'),
  ('CL', 'CL-VS', 'san-felipe', 'catemu', 'Catemu'),
  ('CL', 'CL-VS', 'san-felipe', 'panquehue', 'Panquehue'),
  ('CL', 'CL-VS', 'quillota', 'quillota', 'Quillota'),
  ('CL', 'CL-VS', 'quillota', 'la-calera', 'La Calera'),
  ('CL', 'CL-VS', 'quillota', 'nogales', 'Nogales'),
  ('CL', 'CL-VS', 'quillota', 'hijuelas', 'Hijuelas'),
  ('CL', 'CL-VS', 'quillota', 'la-cruz', 'La Cruz'),
  ('CL', 'CL-VS', 'valparaiso', 'valparaiso', 'Valparaíso'),
  ('CL', 'CL-VS', 'valparaiso', 'vina-del-mar', 'Viña del Mar'),
  ('CL', 'CL-VS', 'valparaiso', 'concon', 'Concón'),
  ('CL', 'CL-VS', 'valparaiso', 'quintero', 'Quintero'),
  ('CL', 'CL-VS', 'valparaiso', 'puchuncavi', 'Puchuncaví'),
  ('CL', 'CL-VS', 'valparaiso', 'casablanca', 'Casablanca'),
  ('CL', 'CL-VS', 'valparaiso', 'juan-fernandez', 'Juan Fernández'),
  ('CL', 'CL-VS', 'marga-marga', 'quilpue', 'Quilpué'),
  ('CL', 'CL-VS', 'marga-marga', 'limache', 'Limache'),
  ('CL', 'CL-VS', 'marga-marga', 'olmue', 'Olmué'),
  ('CL', 'CL-VS', 'marga-marga', 'villa-alemana', 'Villa Alemana'),
  ('CL', 'CL-VS', 'san-antonio', 'algarrobo', 'Algarrobo'),
  ('CL', 'CL-VS', 'san-antonio', 'el-quisco', 'El Quisco'),
  ('CL', 'CL-VS', 'san-antonio', 'el-tabo', 'El Tabo'),
  ('CL', 'CL-VS', 'san-antonio', 'cartagena', 'Cartagena'),
  ('CL', 'CL-VS', 'san-antonio', 'san-antonio', 'San Antonio'),
  ('CL', 'CL-VS', 'san-antonio', 'santo-domingo', 'Santo Domingo'),
  ('CL', 'CL-VS', 'isla-de-pascua', 'isla-de-pascua', 'Isla de Pascua'),
  ('CL', 'CL-LI', 'cachapoal', 'codegua', 'Codegua'),
  ('CL', 'CL-LI', 'cachapoal', 'coinco', 'Coínco'),
  ('CL', 'CL-LI', 'cachapoal', 'coltauco', 'Coltauco'),
  ('CL', 'CL-LI', 'cachapoal', 'donihue', 'Doñihue'),
  ('CL', 'CL-LI', 'cachapoal', 'graneros', 'Graneros'),
  ('CL', 'CL-LI', 'cachapoal', 'las-cabras', 'Las Cabras'),
  ('CL', 'CL-LI', 'cachapoal', 'machali', 'Machalí'),
  ('CL', 'CL-LI', 'cachapoal', 'malloa', 'Malloa'),
  ('CL', 'CL-LI', 'cachapoal', 'olivar', 'Olivar'),
  ('CL', 'CL-LI', 'cachapoal', 'peumo', 'Peumo'),
  ('CL', 'CL-LI', 'cachapoal', 'pichidegua', 'Pichidegua'),
  ('CL', 'CL-LI', 'cachapoal', 'quinta-de-tilcoco', 'Quinta de Tilcoco'),
  ('CL', 'CL-LI', 'cachapoal', 'rancagua', 'Rancagua'),
  ('CL', 'CL-LI', 'cachapoal', 'requinoa', 'Requínoa'),
  ('CL', 'CL-LI', 'cachapoal', 'rengo', 'Rengo'),
  ('CL', 'CL-LI', 'cachapoal', 'mostazal', 'Mostazal'),
  ('CL', 'CL-LI', 'cachapoal', 'san-vicente', 'San Vicente de Tagua Tagua'),
  ('CL', 'CL-LI', 'colchagua', 'chepica', 'Chépica'),
  ('CL', 'CL-LI', 'colchagua', 'chimbarongo', 'Chimbarongo'),
  ('CL', 'CL-LI', 'colchagua', 'lolol', 'Lolol'),
  ('CL', 'CL-LI', 'colchagua', 'nancagua', 'Nancagua'),
  ('CL', 'CL-LI', 'colchagua', 'palmilla', 'Palmilla'),
  ('CL', 'CL-LI', 'colchagua', 'peralillo', 'Peralillo'),
  ('CL', 'CL-LI', 'colchagua', 'placilla', 'Placilla'),
  ('CL', 'CL-LI', 'colchagua', 'pumanque', 'Pumanque'),
  ('CL', 'CL-LI', 'colchagua', 'san-fernando', 'San Fernando'),
  ('CL', 'CL-LI', 'colchagua', 'santa-cruz', 'Santa Cruz'),
  ('CL', 'CL-LI', 'cardenal-caro', 'la-estrella', 'La Estrella'),
  ('CL', 'CL-LI', 'cardenal-caro', 'litueche', 'Litueche'),
  ('CL', 'CL-LI', 'cardenal-caro', 'marchigue', 'Marchigüe'),
  ('CL', 'CL-LI', 'cardenal-caro', 'navidad', 'Navidad'),
  ('CL', 'CL-LI', 'cardenal-caro', 'paredones', 'Paredones'),
  ('CL', 'CL-LI', 'cardenal-caro', 'pichilemu', 'Pichilemu'),
  ('CL', 'CL-ML', 'curico', 'curico', 'Curicó'),
  ('CL', 'CL-ML', 'curico', 'hualane', 'Hualañé'),
  ('CL', 'CL-ML', 'curico', 'licanten', 'Licantén'),
  ('CL', 'CL-ML', 'curico', 'molina', 'Molina'),
  ('CL', 'CL-ML', 'curico', 'rauco', 'Rauco'),
  ('CL', 'CL-ML', 'curico', 'romeral', 'Romeral'),
  ('CL', 'CL-ML', 'curico', 'sagrada-familia', 'Sagrada Familia'),
  ('CL', 'CL-ML', 'curico', 'teno', 'Teno'),
  ('CL', 'CL-ML', 'curico', 'vichuquen', 'Vichuquén'),
  ('CL', 'CL-ML', 'talca', 'talca', 'Talca'),
  ('CL', 'CL-ML', 'talca', 'san-clemente', 'San Clemente'),
  ('CL', 'CL-ML', 'talca', 'pelarco', 'Pelarco'),
  ('CL', 'CL-ML', 'talca', 'pencahue', 'Pencahue'),
  ('CL', 'CL-ML', 'talca', 'maule', 'Maule'),
  ('CL', 'CL-ML', 'talca', 'san-rafael', 'San Rafael'),
  ('CL', 'CL-ML', 'talca', 'curepto', 'Curepto'),
  ('CL', 'CL-ML', 'talca', 'constitucion', 'Constitución'),
  ('CL', 'CL-ML', 'talca', 'empedrado', 'Empedrado'),
  ('CL', 'CL-ML', 'talca', 'rio-claro', 'Río Claro'),
  ('CL', 'CL-ML', 'linares', 'linares', 'Linares'),
  ('CL', 'CL-ML', 'linares', 'san-javier-de-loncomilla', 'San Javier de Loncomilla'),
  ('CL', 'CL-ML', 'linares', 'parral', 'Parral'),
  ('CL', 'CL-ML', 'linares', 'villa-alegre', 'Villa Alegre'),
  ('CL', 'CL-ML', 'linares', 'longavi', 'Longaví'),
  ('CL', 'CL-ML', 'linares', 'colbun', 'Colbún'),
  ('CL', 'CL-ML', 'linares', 'retiro', 'Retiro'),
  ('CL', 'CL-ML', 'linares', 'yerbas-buenas', 'Yerbas Buenas'),
  ('CL', 'CL-ML', 'cauquenes', 'cauquenes', 'Cauquenes'),
  ('CL', 'CL-ML', 'cauquenes', 'chanco', 'Chanco'),
  ('CL', 'CL-ML', 'cauquenes', 'pelluhue', 'Pelluhue'),
  ('CL', 'CL-NB', 'itata', 'cobquecura', 'Cobquecura'),
  ('CL', 'CL-NB', 'itata', 'coelemu', 'Coelemu'),
  ('CL', 'CL-NB', 'itata', 'ninhue', 'Ninhue'),
  ('CL', 'CL-NB', 'itata', 'portezuelo', 'Portezuelo'),
  ('CL', 'CL-NB', 'itata', 'quirihue', 'Quirihue'),
  ('CL', 'CL-NB', 'itata', 'ranquil', 'Ránquil'),
  ('CL', 'CL-NB', 'itata', 'treguaco', 'Treguaco'),
  ('CL', 'CL-NB', 'diguillin', 'bulnes', 'Bulnes'),
  ('CL', 'CL-NB', 'diguillin', 'chillan', 'Chillán'),
  ('CL', 'CL-NB', 'diguillin', 'chillan-viejo', 'Chillán Viejo'),
  ('CL', 'CL-NB', 'diguillin', 'el-carmen', 'El Carmen'),
  ('CL', 'CL-NB', 'diguillin', 'pemuco', 'Pemuco'),
  ('CL', 'CL-NB', 'diguillin', 'pinto', 'Pinto'),
  ('CL', 'CL-NB', 'diguillin', 'quillon', 'Quillón'),
  ('CL', 'CL-NB', 'diguillin', 'san-ignacio', 'San Ignacio'),
  ('CL', 'CL-NB', 'diguillin', 'yungay', 'Yungay'),
  ('CL', 'CL-NB', 'punilla', 'coihueco', 'Coihueco'),
  ('CL', 'CL-NB', 'punilla', 'niquen', 'Ñiquén'),
  ('CL', 'CL-NB', 'punilla', 'san-carlos', 'San Carlos'),
  ('CL', 'CL-NB', 'punilla', 'san-fabian', 'San Fabián'),
  ('CL', 'CL-NB', 'punilla', 'san-nicolas', 'San Nicolás'),
  ('CL', 'CL-BI', 'biobio', 'alto-biobio', 'Alto Biobío'),
  ('CL', 'CL-BI', 'biobio', 'antuco', 'Antuco'),
  ('CL', 'CL-BI', 'biobio', 'cabrero', 'Cabrero'),
  ('CL', 'CL-BI', 'biobio', 'laja', 'Laja'),
  ('CL', 'CL-BI', 'biobio', 'los-angeles', 'Los Ángeles'),
  ('CL', 'CL-BI', 'biobio', 'mulchen', 'Mulchén'),
  ('CL', 'CL-BI', 'biobio', 'nacimiento', 'Nacimiento'),
  ('CL', 'CL-BI', 'biobio', 'negrete', 'Negrete'),
  ('CL', 'CL-BI', 'biobio', 'quilaco', 'Quilaco'),
  ('CL', 'CL-BI', 'biobio', 'quilleco', 'Quilleco'),
  ('CL', 'CL-BI', 'biobio', 'san-rosendo', 'San Rosendo'),
  ('CL', 'CL-BI', 'biobio', 'santa-barbara', 'Santa Bárbara'),
  ('CL', 'CL-BI', 'biobio', 'tucapel', 'Tucapel'),
  ('CL', 'CL-BI', 'biobio', 'yumbel', 'Yumbel'),
  ('CL', 'CL-BI', 'concepcion', 'concepcion', 'Concepción'),
  ('CL', 'CL-BI', 'concepcion', 'coronel', 'Coronel'),
  ('CL', 'CL-BI', 'concepcion', 'chiguayante', 'Chiguayante'),
  ('CL', 'CL-BI', 'concepcion', 'florida', 'Florida'),
  ('CL', 'CL-BI', 'concepcion', 'hualpen', 'Hualpén'),
  ('CL', 'CL-BI', 'concepcion', 'hualqui', 'Hualqui'),
  ('CL', 'CL-BI', 'concepcion', 'lota', 'Lota'),
  ('CL', 'CL-BI', 'concepcion', 'penco', 'Penco'),
  ('CL', 'CL-BI', 'concepcion', 'san-pedro-de-la-paz', 'San Pedro de la Paz'),
  ('CL', 'CL-BI', 'concepcion', 'santa-juana', 'Santa Juana'),
  ('CL', 'CL-BI', 'concepcion', 'talcahuano', 'Talcahuano'),
  ('CL', 'CL-BI', 'concepcion', 'tome', 'Tomé'),
  ('CL', 'CL-BI', 'arauco', 'arauco', 'Arauco'),
  ('CL', 'CL-BI', 'arauco', 'canete', 'Cañete'),
  ('CL', 'CL-BI', 'arauco', 'contulmo', 'Contulmo'),
  ('CL', 'CL-BI', 'arauco', 'curanilahue', 'Curanilahue'),
  ('CL', 'CL-BI', 'arauco', 'lebu', 'Lebu'),
  ('CL', 'CL-BI', 'arauco', 'los-alamos', 'Los Álamos'),
  ('CL', 'CL-BI', 'arauco', 'tirua', 'Tirúa'),
  ('CL', 'CL-AR', 'malleco', 'angol', 'Angol'),
  ('CL', 'CL-AR', 'malleco', 'collipulli', 'Collipulli'),
  ('CL', 'CL-AR', 'malleco', 'curacautin', 'Curacautín'),
  ('CL', 'CL-AR', 'malleco', 'ercilla', 'Ercilla'),
  ('CL', 'CL-AR', 'malleco', 'lonquimay', 'Lonquimay'),
  ('CL', 'CL-AR', 'malleco', 'los-sauces', 'Los Sauces'),
  ('CL', 'CL-AR', 'malleco', 'lumaco', 'Lumaco'),
  ('CL', 'CL-AR', 'malleco', 'puren', 'Purén'),
  ('CL', 'CL-AR', 'malleco', 'renaico', 'Renaico'),
  ('CL', 'CL-AR', 'malleco', 'traiguen', 'Traiguén'),
  ('CL', 'CL-AR', 'malleco', 'victoria', 'Victoria'),
  ('CL', 'CL-AR', 'cautin', 'temuco', 'Temuco'),
  ('CL', 'CL-AR', 'cautin', 'carahue', 'Carahue'),
  ('CL', 'CL-AR', 'cautin', 'cholchol', 'Cholchol'),
  ('CL', 'CL-AR', 'cautin', 'cunco', 'Cunco'),
  ('CL', 'CL-AR', 'cautin', 'curarrehue', 'Curarrehue'),
  ('CL', 'CL-AR', 'cautin', 'freire', 'Freire'),
  ('CL', 'CL-AR', 'cautin', 'galvarino', 'Galvarino'),
  ('CL', 'CL-AR', 'cautin', 'gorbea', 'Gorbea'),
  ('CL', 'CL-AR', 'cautin', 'lautaro', 'Lautaro'),
  ('CL', 'CL-AR', 'cautin', 'loncoche', 'Loncoche'),
  ('CL', 'CL-AR', 'cautin', 'melipeuco', 'Melipeuco'),
  ('CL', 'CL-AR', 'cautin', 'nueva-imperial', 'Nueva Imperial'),
  ('CL', 'CL-AR', 'cautin', 'padre-las-casas', 'Padre Las Casas'),
  ('CL', 'CL-AR', 'cautin', 'perquenco', 'Perquenco'),
  ('CL', 'CL-AR', 'cautin', 'pitrufquen', 'Pitrufquén'),
  ('CL', 'CL-AR', 'cautin', 'pucon', 'Pucón'),
  ('CL', 'CL-AR', 'cautin', 'saavedra', 'Saavedra'),
  ('CL', 'CL-AR', 'cautin', 'teodoro-schmidt', 'Teodoro Schmidt'),
  ('CL', 'CL-AR', 'cautin', 'tolten', 'Toltén'),
  ('CL', 'CL-AR', 'cautin', 'vilcun', 'Vilcún'),
  ('CL', 'CL-AR', 'cautin', 'villarrica', 'Villarrica'),
  ('CL', 'CL-LR', 'valdivia', 'valdivia', 'Valdivia'),
  ('CL', 'CL-LR', 'valdivia', 'corral', 'Corral'),
  ('CL', 'CL-LR', 'valdivia', 'lanco', 'Lanco'),
  ('CL', 'CL-LR', 'valdivia', 'los-lagos', 'Los Lagos'),
  ('CL', 'CL-LR', 'valdivia', 'mariquina', 'Mariquina'),
  ('CL', 'CL-LR', 'valdivia', 'mafil', 'Máfil'),
  ('CL', 'CL-LR', 'valdivia', 'paillaco', 'Paillaco'),
  ('CL', 'CL-LR', 'valdivia', 'panguipulli', 'Panguipulli'),
  ('CL', 'CL-LR', 'ranco', 'la-union', 'La Unión'),
  ('CL', 'CL-LR', 'ranco', 'futrono', 'Futrono'),
  ('CL', 'CL-LR', 'ranco', 'lago-ranco', 'Lago Ranco'),
  ('CL', 'CL-LR', 'ranco', 'rio-bueno', 'Río Bueno'),
  ('CL', 'CL-LL', 'osorno', 'osorno', 'Osorno'),
  ('CL', 'CL-LL', 'osorno', 'puerto-octay', 'Puerto Octay'),
  ('CL', 'CL-LL', 'osorno', 'purranque', 'Purranque'),
  ('CL', 'CL-LL', 'osorno', 'puyehue', 'Puyehue'),
  ('CL', 'CL-LL', 'osorno', 'rio-negro', 'Río Negro'),
  ('CL', 'CL-LL', 'osorno', 'san-pablo', 'San Pablo'),
  ('CL', 'CL-LL', 'osorno', 'san-juan-de-la-costa', 'San Juan de la Costa'),
  ('CL', 'CL-LL', 'llanquihue', 'calbuco', 'Calbuco'),
  ('CL', 'CL-LL', 'llanquihue', 'cochamo', 'Cochamó'),
  ('CL', 'CL-LL', 'llanquihue', 'fresia', 'Fresia'),
  ('CL', 'CL-LL', 'llanquihue', 'frutillar', 'Frutillar'),
  ('CL', 'CL-LL', 'llanquihue', 'llanquihue', 'Llanquihue'),
  ('CL', 'CL-LL', 'llanquihue', 'los-muermos', 'Los Muermos'),
  ('CL', 'CL-LL', 'llanquihue', 'maullin', 'Maullín'),
  ('CL', 'CL-LL', 'llanquihue', 'puerto-montt', 'Puerto Montt'),
  ('CL', 'CL-LL', 'llanquihue', 'puerto-varas', 'Puerto Varas'),
  ('CL', 'CL-LL', 'chiloe', 'ancud', 'Ancud'),
  ('CL', 'CL-LL', 'chiloe', 'castro', 'Castro'),
  ('CL', 'CL-LL', 'chiloe', 'chonchi', 'Chonchi'),
  ('CL', 'CL-LL', 'chiloe', 'curaco-de-velez', 'Curaco de Vélez'),
  ('CL', 'CL-LL', 'chiloe', 'dalcahue', 'Dalcahue'),
  ('CL', 'CL-LL', 'chiloe', 'puqueldon', 'Puqueldón'),
  ('CL', 'CL-LL', 'chiloe', 'queilen', 'Queilén'),
  ('CL', 'CL-LL', 'chiloe', 'quellon', 'Quellón'),
  ('CL', 'CL-LL', 'chiloe', 'quemchi', 'Quemchi'),
  ('CL', 'CL-LL', 'chiloe', 'quinchao', 'Quinchao'),
  ('CL', 'CL-LL', 'palena', 'futaleufu', 'Futaleufú'),
  ('CL', 'CL-LL', 'palena', 'hualaihue', 'Hualaihué'),
  ('CL', 'CL-LL', 'palena', 'palena', 'Palena'),
  ('CL', 'CL-LL', 'palena', 'chaiten', 'Chaitén'),
  ('CL', 'CL-AI', 'coihaique', 'coihaique', 'Coihaique'),
  ('CL', 'CL-AI', 'coihaique', 'lago-verde', 'Lago Verde'),
  ('CL', 'CL-AI', 'aysen', 'aysen', 'Aysén'),
  ('CL', 'CL-AI', 'aysen', 'cisnes', 'Cisnes'),
  ('CL', 'CL-AI', 'aysen', 'guaitecas', 'Guaitecas'),
  ('CL', 'CL-AI', 'general-carrera', 'chile-chico', 'Chile Chico'),
  ('CL', 'CL-AI', 'general-carrera', 'rio-ibanez', 'Río Ibáñez'),
  ('CL', 'CL-AI', 'capitan-prat', 'cochrane', 'Cochrane'),
  ('CL', 'CL-AI', 'capitan-prat', 'o-higgins', 'O''Higgins'),
  ('CL', 'CL-AI', 'capitan-prat', 'tortel', 'Tortel'),
  ('CL', 'CL-MA', 'ultima-esperanza', 'puerto-natales', 'Puerto Natales'),
  ('CL', 'CL-MA', 'ultima-esperanza', 'torres-del-paine', 'Torres del Paine'),
  ('CL', 'CL-MA', 'magallanes', 'laguna-blanca', 'Laguna Blanca'),
  ('CL', 'CL-MA', 'magallanes', 'punta-arenas', 'Punta Arenas'),
  ('CL', 'CL-MA', 'magallanes', 'rio-verde', 'Río Verde'),
  ('CL', 'CL-MA', 'magallanes', 'san-gregorio', 'San Gregorio'),
  ('CL', 'CL-MA', 'tierra-del-fuego', 'porvenir', 'Porvenir'),
  ('CL', 'CL-MA', 'tierra-del-fuego', 'primavera', 'Primavera'),
  ('CL', 'CL-MA', 'tierra-del-fuego', 'timaukel', 'Timaukel'),
  ('CL', 'CL-MA', 'antartica-chilena', 'cabo-de-hornos', 'Cabo de Hornos'),
  ('CL', 'CL-MA', 'antartica-chilena', 'antartica', 'Antártica'),
  ('CL', 'CL-RM', 'chacabuco', 'colina', 'Colina'),
  ('CL', 'CL-RM', 'chacabuco', 'lampa', 'Lampa'),
  ('CL', 'CL-RM', 'chacabuco', 'tiltil', 'Tiltil'),
  ('CL', 'CL-RM', 'cordillera', 'puente-alto', 'Puente Alto'),
  ('CL', 'CL-RM', 'cordillera', 'san-jose-de-maipo', 'San José de Maipo'),
  ('CL', 'CL-RM', 'cordillera', 'pirque', 'Pirque'),
  ('CL', 'CL-RM', 'maipo', 'san-bernardo', 'San Bernardo'),
  ('CL', 'CL-RM', 'maipo', 'buin', 'Buin'),
  ('CL', 'CL-RM', 'maipo', 'paine', 'Paine'),
  ('CL', 'CL-RM', 'maipo', 'calera-de-tango', 'Calera de Tango'),
  ('CL', 'CL-RM', 'talagante', 'isla-de-maipo', 'Isla de Maipo'),
  ('CL', 'CL-RM', 'talagante', 'el-monte', 'El Monte'),
  ('CL', 'CL-RM', 'talagante', 'padre-hurtado', 'Padre Hurtado'),
  ('CL', 'CL-RM', 'talagante', 'penaflor', 'Peñaflor'),
  ('CL', 'CL-RM', 'talagante', 'talagante', 'Talagante'),
  ('CL', 'CL-RM', 'melipilla', 'curacavi', 'Curacaví'),
  ('CL', 'CL-RM', 'melipilla', 'maria-pinto', 'María Pinto'),
  ('CL', 'CL-RM', 'melipilla', 'melipilla', 'Melipilla'),
  ('CL', 'CL-RM', 'melipilla', 'san-pedro', 'San Pedro'),
  ('CL', 'CL-RM', 'melipilla', 'alhue', 'Alhué'),
  ('CL', 'CL-RM', 'santiago', 'cerrillos', 'Cerrillos'),
  ('CL', 'CL-RM', 'santiago', 'cerro-navia', 'Cerro Navia'),
  ('CL', 'CL-RM', 'santiago', 'conchali', 'Conchalí'),
  ('CL', 'CL-RM', 'santiago', 'el-bosque', 'El Bosque'),
  ('CL', 'CL-RM', 'santiago', 'estacion-central', 'Estación Central'),
  ('CL', 'CL-RM', 'santiago', 'huechuraba', 'Huechuraba'),
  ('CL', 'CL-RM', 'santiago', 'independencia', 'Independencia'),
  ('CL', 'CL-RM', 'santiago', 'la-cisterna', 'La Cisterna'),
  ('CL', 'CL-RM', 'santiago', 'la-granja', 'La Granja'),
  ('CL', 'CL-RM', 'santiago', 'la-florida', 'La Florida'),
  ('CL', 'CL-RM', 'santiago', 'la-pintana', 'La Pintana'),
  ('CL', 'CL-RM', 'santiago', 'la-reina', 'La Reina'),
  ('CL', 'CL-RM', 'santiago', 'las-condes', 'Las Condes'),
  ('CL', 'CL-RM', 'santiago', 'lo-barnechea', 'Lo Barnechea'),
  ('CL', 'CL-RM', 'santiago', 'lo-espejo', 'Lo Espejo'),
  ('CL', 'CL-RM', 'santiago', 'lo-prado', 'Lo Prado'),
  ('CL', 'CL-RM', 'santiago', 'macul', 'Macul'),
  ('CL', 'CL-RM', 'santiago', 'maipu', 'Maipú'),
  ('CL', 'CL-RM', 'santiago', 'nunoa', 'Ñuñoa'),
  ('CL', 'CL-RM', 'santiago', 'pedro-aguirre-cerda', 'Pedro Aguirre Cerda'),
  ('CL', 'CL-RM', 'santiago', 'penalolen', 'Peñalolén'),
  ('CL', 'CL-RM', 'santiago', 'providencia', 'Providencia'),
  ('CL', 'CL-RM', 'santiago', 'pudahuel', 'Pudahuel'),
  ('CL', 'CL-RM', 'santiago', 'quilicura', 'Quilicura'),
  ('CL', 'CL-RM', 'santiago', 'quinta-normal', 'Quinta Normal'),
  ('CL', 'CL-RM', 'santiago', 'recoleta', 'Recoleta'),
  ('CL', 'CL-RM', 'santiago', 'renca', 'Renca'),
  ('CL', 'CL-RM', 'santiago', 'san-miguel', 'San Miguel'),
  ('CL', 'CL-RM', 'santiago', 'san-joaquin', 'San Joaquín'),
  ('CL', 'CL-RM', 'santiago', 'san-ramon', 'San Ramón'),
  ('CL', 'CL-RM', 'santiago', 'santiago', 'Santiago'),
  ('CL', 'CL-RM', 'santiago', 'vitacura', 'Vitacura')
on conflict (address_level0_id, address_level1_id, address_level2_id, address_level3_id) do nothing;
