#!/usr/bin/env node
/**
 * Writes .env.development.local for all apps from `supabase status -o env`.
 * Configures environment variables for local development.
 * Usage: Run after `pnpm db:start`: pnpm db:env:development
 */

import { execSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { dedent } from "ts-dedent";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "../..");
const SUPABASE_DIR = join(ROOT, "packages/supabase");
const TARGET_FILENAME = ".env.development.local";
const TARGET_PATH = join(ROOT, TARGET_FILENAME);
/** apps/platform reads env via @next/env loadEnvConfig — must live in the app dir  */
const PLATFORM_ENV_PATH = join(ROOT, "apps/platform", TARGET_FILENAME);
const CLAUDE_SETTINGS_DIR = join(ROOT, ".claude");
const CLAUDE_SETTINGS_PATH = join(CLAUDE_SETTINGS_DIR, "settings.local.json");

// config.toml decodes this bool on every supabase command; unset → "parse value as 'bool'".
process.env["SUPABASE_AUTH_ALLOW_DYNAMIC_REGISTRATION"] ??= "true";

let raw: string;
try {
  raw = execSync("pnpm db:status:env", { cwd: SUPABASE_DIR, encoding: "utf-8" });
} catch {
  console.warn("Supabase not running, starting it now...");
  execSync("pnpm db:start", { cwd: SUPABASE_DIR, stdio: "inherit" });
  raw = execSync("pnpm db:status:env", { cwd: SUPABASE_DIR, encoding: "utf-8" });
}

const env: Record<string, string> = Object.fromEntries(
  raw
    .split("\n")
    .filter((line) => line.includes("="))
    .map((line) => {
      const idx = line.indexOf("=");
      return [line.slice(0, idx).trim(), line.slice(idx + 1).trim()];
    }),
);

const SUPABASE_ANON_KEY = env["ANON_KEY"] ?? "";
const SUPABASE_SERVICE_ROLE_KEY = env["SERVICE_ROLE_KEY"] ?? "";
const DATABASE_URL = env["DB_URL"] ?? "";

// When running on an exe.dev VM, browser-facing URLs must use the VM's public host
// `<vm>.exe.xyz` (TLS terminated by exe.dev's proxy, ports forwarded in 3000-9999) instead
// of `127.0.0.1`/lvh.me. Set by exe-dev-setup.sh. Server-only URLs (DATABASE_URL) stay local
// because the app runs ON the VM. See scripts/development/exe-dev-setup.sh.
const EXE_HOST = process.env["EXE_HOST"];

/** Rewrite a local `http://127.0.0.1:<port>` URL to the public `https://<exe-host>:<port>`. No-op locally. */
function PUBLIC_URL(localUrl: string): string {
  if (!EXE_HOST) return localUrl;
  try {
    const u = new URL(localUrl);
    return `https://${EXE_HOST}${u.port ? `:${u.port}` : ""}`;
  } catch {
    return localUrl;
  }
}

const SUPABASE_URL = PUBLIC_URL(env["API_URL"] ?? "http://127.0.0.1:54421");
const APEX_HOSTNAME = EXE_HOST ?? "lvh.me";

/** Environment variables for local development, including public and secret values. */
const variables: Array<{ key: string; value: string; secret: boolean }> = [
  { key: "NEXT_PUBLIC_SUPABASE_URL", value: SUPABASE_URL, secret: false },
  { key: "NEXT_PUBLIC_SUPABASE_ANON_KEY", value: SUPABASE_ANON_KEY, secret: false },
  { key: "NEXT_PUBLIC_COOKIE_DOMAIN", value: APEX_HOSTNAME, secret: false },
  { key: "NEXT_PUBLIC_APEX_HOSTNAME", value: APEX_HOSTNAME, secret: false },
  {
    key: "NEXT_PUBLIC_DEV_MAILBOX_URL",
    value: PUBLIC_URL(env["INBUCKET_URL"] ?? "http://localhost:54424"),
    secret: false,
  },
  { key: "SUPABASE_SERVICE_ROLE_KEY", value: SUPABASE_SERVICE_ROLE_KEY, secret: true },
  { key: "DATABASE_URL", value: DATABASE_URL, secret: true },
];

const lines = variables.map(({ key, value, secret }) => {
  const display = value.length === 0 ? "(empty)" : secret ? "********" : value;
  console.log(`  - setting "${key}"=${display}`);
  return `${key}=${value}`;
});

const APP_PORT = process.env["PORT"] ?? "7003";
const APP_URL = `https://${APEX_HOSTNAME}:${APP_PORT}`;
const apiLocal = env["API_URL"] ?? "http://127.0.0.1:54321";
const studioPort = process.env["SUPABASE_STUDIO_PORT"];
const STUDIO_URL = studioPort ? PUBLIC_URL(apiLocal.replace(/:\d+/, `:${studioPort}`)) : "(unknown)";
const MAILBOX_URL = PUBLIC_URL(env["INBUCKET_URL"] ?? env["MAILPIT_URL"] ?? "http://localhost:54324");

const SUPABASE_CLI_KEYS = [
  "SUPABASE_PROJECT_ID",
  "SUPABASE_SHADOW_PORT",
  "SUPABASE_API_PORT",
  "SUPABASE_DB_PORT",
  "SUPABASE_STUDIO_PORT",
  "SUPABASE_INBUCKET_PORT",
  "SUPABASE_ANALYTICS_PORT",
  "SUPABASE_AUTH_SITE_URL",
  "SUPABASE_AUTH_WEBAUTHN_RP_ORIGINS",
  "SUPABASE_AUTH_ALLOW_DYNAMIC_REGISTRATION",
] as const;

const supabaseCliLines = SUPABASE_CLI_KEYS.map((k) => [k, process.env[k]] as const)
  .filter(([, v]) => v !== undefined)
  .map(([k, v]) => `${k}=${v}`);

// Conductor/exe.dev assign ports at runtime; this is the source of truth.
writeFileSync(
  TARGET_PATH,
  dedent`
    # Dev env — this worktree
    # Generated by pnpm db:env:development — per-worktree URLs/ports (Conductor/exe.dev assign at runtime)
    #
    # App:             ${APP_URL}
    # Supabase API:    ${SUPABASE_URL}
    # Supabase Studio: ${STUDIO_URL}
    # Mailbox:         ${MAILBOX_URL}
    # Database:        ${DATABASE_URL}

    ${supabaseCliLines.join("\n")}

    ${lines.join("\n")}
  `,
);
console.log(`wrote ${TARGET_FILENAME} (app: ${APP_URL})`);

// Mirror into apps/platform so graphql-codegen (via @next/env loadEnvConfig) picks up dynamic ports.
// apps/platform/.env.local has default fallback values; this .env.development.local overrides them.
writeFileSync(PLATFORM_ENV_PATH, `${lines}\n`);
console.log(`wrote apps/platform/${TARGET_FILENAME}`);

/**
 * Injects DATABASE_URL into .claude/settings.local.json.
 */
if (DATABASE_URL.length > 0) {
  mkdirSync(CLAUDE_SETTINGS_DIR, { recursive: true });
  let settings: Record<string, unknown> = {};
  if (existsSync(CLAUDE_SETTINGS_PATH)) {
    try {
      settings = JSON.parse(readFileSync(CLAUDE_SETTINGS_PATH, "utf-8"));
    } catch {
      console.warn(`could not parse ${CLAUDE_SETTINGS_PATH} — overwriting`);
    }
  }
  const block = (settings["env"] as Record<string, string> | undefined) ?? {};
  block["DATABASE_URL"] = DATABASE_URL.replace(/^"(.*)"$/, "$1");
  settings["env"] = block;
  writeFileSync(CLAUDE_SETTINGS_PATH, `${JSON.stringify(settings, null, 2)}\n`);
  console.log("wrote DATABASE_URL into .claude/settings.local.json (restart Claude to pick it up)");
}

console.log("✅ done env.setup.ts");
