import { updateSession } from "@packages/supabase/client.middleware";
import { createServiceRoleClient } from "@packages/supabase/client.service";
import { JWT_DECODE_PAYLOAD } from "@packages/utils/jwt";
import { type NextRequest, NextResponse } from "next/server";
import { APEX_HOSTNAME, APP_HOST } from "~/lib/constants";
import { debug } from "~/lib/debug";
import { EXTRACT_LOCALE_FROM_PATH, LOCALE_COOKIE, RESOLVE_LOCALE_FROM_REQUEST, type SupportedLocale } from "~/lib/i18n";

const log = debug("proxy");

type TenantClaim = { id: number; slug: string };
type JwtPayload = { app_metadata?: { tenants?: TenantClaim[] } };

async function resolveTenantIdFromSlug(slug: string): Promise<number | null> {
  const supabase = createServiceRoleClient();
  const { data } = await supabase
    .from("tenants")
    .select("tenant_id, tenant_disabled_at")
    .eq("tenant_slug", slug)
    .maybeSingle();
  if (!data || data.tenant_disabled_at) return null;
  return data.tenant_id;
}

function extractSubdomain(hostname: string): string | null {
  // Strip port before matching — port varies per dev session but the domain is stable.
  const host = hostname.split(":")[0] ?? "";
  if (!host) return null;
  if (host === APEX_HOSTNAME || host === `www.${APEX_HOSTNAME}`) return null;
  if (!host.endsWith(`.${APEX_HOSTNAME}`)) return null;
  const slug = host.slice(0, host.length - APEX_HOSTNAME.length - 1);
  if (!slug || slug === "www") return null;
  return slug;
}

function isLocalizedPublicPath(pathAfterLocale: string): boolean {
  return (
    pathAfterLocale === "/" ||
    pathAfterLocale === "/auth" ||
    pathAfterLocale.startsWith("/auth/") ||
    // Metadata files generated by Next.js conventions (opengraph-image.tsx, twitter-image.tsx, icon.tsx).
    pathAfterLocale === "/opengraph-image" ||
    pathAfterLocale === "/twitter-image" ||
    pathAfterLocale === "/icon"
  );
}

function copyCookies(from: NextResponse, to: NextResponse): NextResponse {
  for (const cookie of from.cookies.getAll()) to.cookies.set(cookie);
  return to;
}

// Persist the locale on the response so the browser stores it for next request.
// The matching mutation on `request.cookies` happens before `updateSession` runs (see proxy()
// below) — without that, server components in the same request would still read the stale value.
function setLocaleCookieOnResponse(response: NextResponse, locale: SupportedLocale): NextResponse {
  const cookieDomain = process.env["NEXT_PUBLIC_COOKIE_DOMAIN"];
  response.cookies.set(LOCALE_COOKIE, locale, {
    path: "/",
    maxAge: 60 * 60 * 24 * 365,
    sameSite: "lax",
    ...(cookieDomain ? { domain: cookieDomain } : {}),
  });
  return response;
}

export async function proxy(request: NextRequest) {
  const hostname = request.headers.get("host") ?? "";
  const pathname = request.nextUrl.pathname;
  const proto = request.headers.get("x-forwarded-proto") ?? request.nextUrl.protocol.replace(":", "");

  // Classify the host: apex/www, tenant subdomain, or unknown (custom apex, phase 2).
  // Strip port for matching so the proxy works on any dev port, not just the configured default.
  const hostnameBase = hostname.split(":")[0] ?? "";
  let isApex = hostnameBase === APEX_HOSTNAME || hostnameBase === `www.${APEX_HOSTNAME}`;
  let slugFromHost: string | null = null;
  // Vercel preview/dev deployments come in on `*.vercel.app` hosts that won't match APEX_HOSTNAME.
  // Treat them as apex so previews stay reachable instead of bouncing to production.
  const vercelEnv = process.env["VERCEL_ENV"];
  const isVercelNonProd = vercelEnv === "preview" || vercelEnv === "development";
  if (!isApex) {
    if (hostnameBase.endsWith(`.${APEX_HOSTNAME}`)) {
      slugFromHost = extractSubdomain(hostname);
    } else if (isVercelNonProd) {
      isApex = true;
    } else {
      // Unknown host (localhost/127.0.0.1/custom apex). Custom apexes are phase 2 —
      // for now, bounce to the configured apex so cookies/session land on the right origin.
      const apexUrl = new URL(`${pathname}${request.nextUrl.search}`, `${proto}://${APP_HOST}`);
      return NextResponse.redirect(apexUrl);
    }
  }

  // /health stays canonical at the apex with no locale prefix.
  if (pathname === "/health") {
    if (isApex) {
      const { response } = await updateSession(request);
      return response;
    }
    return NextResponse.redirect(new URL("/health", `${proto}://${APP_HOST}`));
  }

  // Detect locale from URL first segment; if missing, resolve from cookie/header and redirect.
  const { locale: localeFromPath, pathAfterLocale } = EXTRACT_LOCALE_FROM_PATH(pathname);
  if (!localeFromPath) {
    const detected = RESOLVE_LOCALE_FROM_REQUEST(request);
    const url = request.nextUrl.clone();
    const trailingPath = pathname === "/" ? "" : pathname;
    url.pathname = `/${detected}${trailingPath}`;
    return setLocaleCookieOnResponse(NextResponse.redirect(url), detected);
  }
  const locale = localeFromPath;

  // Mutate the incoming request's cookie BEFORE updateSession creates its NextResponse.next({request}).
  // Downstream server components (root layout, server actions) read cookies via next/headers `cookies()`,
  // which reflects the request snapshot — so if we only set on the response, server-rendered output
  // (notably <html lang>) reads the previous request's cookie and falls out of sync with the URL.
  request.cookies.set(LOCALE_COOKIE, locale);

  const { response: sessionResponse, supabase } = await updateSession(request);

  // Tenant subdomain: send /auth/* and /onboarding/* back to the apex so auth lives at one origin.
  if (slugFromHost) {
    if (pathAfterLocale.startsWith("/auth") || pathAfterLocale.startsWith("/onboarding")) {
      const url = new URL(`/${locale}${pathAfterLocale}`, `${proto}://${APP_HOST}`);
      url.search = request.nextUrl.search;
      return setLocaleCookieOnResponse(NextResponse.redirect(url), locale);
    }
  }

  // Apex public routes — no auth required, but logged-in users shouldn't see the auth entry pages
  // (the form's server action gets bound to the wrong route after a client transition from /dashboard
  // and posts to the previous URL, producing "unexpected response from server").
  if (isApex && isLocalizedPublicPath(pathAfterLocale)) {
    const isAuthEntryPath = pathAfterLocale === "/auth" || pathAfterLocale.startsWith("/auth/email");
    if (isAuthEntryPath) {
      const {
        data: { session },
      } = await supabase.auth.getSession();
      if (session) {
        return setLocaleCookieOnResponse(
          NextResponse.redirect(new URL(`/${locale}/dashboard`, `${proto}://${APP_HOST}`)),
          locale,
        );
      }
    }
    return setLocaleCookieOnResponse(sessionResponse, locale);
  }

  // Auth gate.
  const {
    data: { session },
  } = await supabase.auth.getSession();
  if (!session) {
    const next = `${proto}://${hostname}${pathname}${request.nextUrl.search}`;
    const authUrl = new URL(`/${locale}/auth`, `${proto}://${APP_HOST}`);
    authUrl.searchParams.set("next", next);
    return setLocaleCookieOnResponse(NextResponse.redirect(authUrl), locale);
  }

  // Hook-injected claims (tenants) only exist in the JWT, not on the DB user record.
  // The `onboarded` claim is no longer used as a gate here — onboarding completion is
  // surfaced to users via page-level UX (e.g. a banner / nudge) rather than a hard redirect,
  // so users can land on /dashboard or any other route mid-onboarding without being bounced.
  const claims = JWT_DECODE_PAYLOAD(session.access_token) as JwtPayload | null;
  const tenants = claims?.["app_metadata"]?.["tenants"] ?? [];

  // Subdomain → membership check + rewrite to /[locale]/[tenant_slug]{pathAfterLocale}.
  if (slugFromHost) {
    const tenant_id = await resolveTenantIdFromSlug(slugFromHost);
    if (!tenant_id) {
      log.warn("unknown or disabled tenant subdomain", { slug: slugFromHost, hostname });
      return new NextResponse("Tenant not found", { status: 404 });
    }
    if (!tenants.some((t) => t["id"] === tenant_id)) {
      log.warn("user lacks membership for tenant subdomain", {
        slug: slugFromHost,
        tenant_id,
        user_tenant_ids: tenants.map((t) => t["id"]),
      });
      return new NextResponse("No tienes acceso a esta empresa.", { status: 403 });
    }
    const url = request.nextUrl.clone();
    url.pathname = `/${locale}/${slugFromHost}${pathAfterLocale}`;
    const rewritten = NextResponse.rewrite(url, { request });
    return setLocaleCookieOnResponse(copyCookies(sessionResponse, rewritten), locale);
  }

  // Apex protected paths (/[locale]/dashboard, /[locale]/tenants/create, /[locale]/[tenant_slug]/...)
  // — page-level membership for tenant routes is handled by app/[locale]/[tenant_slug]/page.tsx
  // (notFound() if slug isn't in JWT).
  return setLocaleCookieOnResponse(sessionResponse, locale);
}

export const config = {
  matcher: ["/((?!api|_next/static|_next/image|favicon.ico|robots.txt|sitemap.xml|llms.txt).*)"],
};
